Testing lib
borangoher/frontend-demo pull request #24
Opened 2023-02-08 06:18 UTC by borangoher

close #12. This PR should now display only the relevant changes.

2023-02-08 07:36 UTC, yeged commented on src/Components/payment-form/__tests__/paymentForm.test.js
> +  ).toBeInTheDocument();
is it duplicated
`expect(
    screen.getByText(/payment.errorMessages.cardholderNameMin/i)
  ).toBeInTheDocument();`

2023-02-08 08:12 UTC, yeged approved these changes

2023-02-08 09:40 UTC, ozgunbal requested changes

2023-02-08 09:40 UTC, ozgunbal commented on src/Components/login/__tests__/Login.test.js
> +  fireEvent.change(usernameElement, { target: { value: "abcde" } });
try to use https://testing-library.com/docs/user-event/intro/ . This is better for simulating user's behaviors. fireEvent assumes some internal logic. Black box testing is more beneficial in our cases.

2023-02-08 09:40 UTC, ozgunbal commented on src/Components/login/__tests__/Login.test.js
> +
- Recommending to read this article: https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#adding-aria--role-and-other-accessibility-attributes-incorrectly
- After handling failed login in #25, add a test for un-auth entry.(send 401 from msw for test case, then expect to see error message in the document)

2023-02-13 13:04 UTC, ozgunbal approved these changes
Approved but expecting to finish #27 in a different PR.

2023-02-13 13:15 UTC, merged