Typescript
borangoher/frontend-demo pull request #26
Opened 2023-02-13 11:45 UTC by borangoher

close #5.

2023-02-13 12:33 UTC, yeged commented on src/App.tsx
> +import React from "react";
We import React on top of file.

2023-02-13 12:33 UTC, yeged commented on src/Components/payment-form/PaymentForm.tsx
>    });
Can you define form prop types in constant file and import in here to use at useForm. Same for Login.

`useForm<FormProps>`

```
interface FormProps {
    cardholderName: string,
    ...
}
```

2023-02-13 12:33 UTC, yeged commented on src/Components/payment-form/PaymentForm.tsx
> +  const onSubmit = (data: object) => console.log(data);
Will be `data: FormProps`

2023-02-13 12:33 UTC, yeged commented on src/Components/payment-form/PaymentForm.tsx
> +                      {t(errors.cardholderName.message as string, {
You shouldn't need to define as string here.

2023-02-13 12:33 UTC, yeged commented on src/Components/payment-form/paymentForm.validation.ts
>      )
can you add schema type. Same for Login.

`const schema: Yup.SchemaOf<FormProps> = ...`

2023-02-13 12:41 UTC, yeged commented on src/Components/payment-form/paymentForm.validation.ts
>      )
if you get error you can use `default('')`

`Yup.string().notRequired().default('')`

2023-02-13 12:45 UTC, yeged commented on src/Components/LoginContext.tsx
> +type LoginAction = {type: "log in"} | {type: "log out"};
You can use enum here. If its possible with useReducer
 
```
export enum LoginActionState {
    LOGIN,
    LOGOUT
}

interface LoginAction {
  type: LoginActionState ;
}
```
or another way.

2023-02-13 13:42 UTC, borangoher commented on src/Components/payment-form/PaymentForm.tsx
> +                      {t(errors.cardholderName.message as string, {
Typescript won't compile unless I include ```as string```. If I understand the error message correctly, Typescript expects ```errors.cardholderName.message``` to be a ```string | undefined``` and expects the input to ```t``` to be a ```string | string[]```. So it won't let me pass the argument if I don't narrow the type to just ```string```.

2023-02-14 09:19 UTC, yeged commented on src/Components/payment-form/PaymentForm.tsx
> +                      {t(errors.cardholderName.message as string, {
Nice research.

I was using `t(errors.amount.message || '')` logical or operator. But we don't want to call t function every time so, we use now `errors.amount ? t(errors.amount.message) : ''` conditional (ternary) operator.

2023-02-14 09:19 UTC, yeged commented on src/Components/payment-form/paymentForm.validation.ts
>      )
You don't need to add default() if it's required. You wont get error

2023-02-15 07:37 UTC, ozgunbal requested changes

2023-02-15 07:37 UTC, ozgunbal commented on src/api/index.ts
> +export const loginUser = async (userData: object) => {
don't prefer `object`. this is a generic type. This is actually `FormProps` but you can import as `UserData` in here.
`import { FormProps as UserData } from "../Components/payment-form/paymentForm.constant";`

2023-02-15 08:39 UTC, ozgunbal approved these changes

2023-02-15 09:20 UTC, merged